   # Użyj obrazu bazowego z Pythona
   FROM python:3.12

   # Ustaw katalog roboczy
   WORKDIR /app

   # Skopiuj pliki do kontenera
   COPY requirements.txt requirements.txt
   COPY app.py app.py

   # Zainstaluj zależności
   RUN pip install -r requirements.txt

   # Uruchom aplikację
   CMD ["python", "app.py"]